name: movie_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  bloc: ^8.1.2
  cached_network_image: ^3.2.3
  dartz: ^0.10.1
  dio: ^5.3.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_spinkit: ^5.2.0
  get_it: ^7.6.4
  go_router: ^10.1.2
  shared_preferences: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
